from infoproc import boolean2
from ipdb import set_trace
from infoproc.boolean2 import Model

text = """
MLK3= Random
Rac= Random
Graf= Random
RalBP1= Random
Ca= Random
Raf= Random
alpha_iL= Random
IL1_TNFR= Random
SHP2= Random
Rho= Random
PLD= Random
B_Arrestin= Random
Integrins= Random
DOCK180= Random
Rap1= Random
Csk= Random
RasGRF_GRP= Random
Palpha_sR= Random
Raf_Rest= Random
p38= Random
PKC= Random
EGF= Random
PTPPEST= Random
PI4K= Random
PDE4= Random
PIP_4= Random
alpha_sR= Random
alpha_iR= Random
MKK6= Random
Trx= Random
MLCK= Random
Pix_Cool= Random
DAG= Random
EGFR= Random
RhoGDI= Random
alpha_1213L= Random
Ral= Random
ECM= Random
alpha_1213R= Random
Gas= Random
MLK1= Random
SAPK= Random
p90RSK= Random
PLC_B= Random
IP3= Random
RKIP= Random
PTPa= Random
Gbg_1213= Random
Mekk2= Random
Shc= Random
Grb2= Random
alpha_qL= Random
Palpha_qR= Random
Gbg_s= Random
MKPs= Random
B_Parvin= Random
Trafs= Random
Tiam= Random
alpha_sL= Random
Mekk1= Random
Arp_23= Random
MKK3= Random
Crk= Random
p115RhoGEF= Random
Nck= Random
RhoK= Random
ASK1= Random
PLA2= Random
Vinc= Random
RalGDS= Random
ILK= Random
cAMP= Random
Fak= Random
Mekk3= Random
CaM= Random
PDK1= Random
PKC_primed= Random
MLK2= Random
ARF= Random
TAK1= Random
Sos= Random
Gbg_i= Random
Erk= Random
CaMKK= Random
Raf_Loc= Random
PLC_g= Random
NIK= Random
PTEN= Random
TAO_12= Random
WASP= Random
MLCP= Random
Mekk4= Random
ExtPump= Random
PAK= Random
IL1_TNF= Random
Cdc42= Random
p190RhoGAP= Random
Palpha_1213R= Random
Stress= Random
Sek1= Random
Akt= Random
PI3K= Random
CaMK= Random
Src= Random
Cbp= Random
IP3R1= Random
GCK= Random
AND_34= Random
Cas= Random
Myosin= Random
PKA= Random
Tab_12= Random
Gai= Random
Ras= Random
PP2A= Random
alpha_qR= Random
GRK= Random
PIP2_45= Random
Mek= Random
Raf_DeP= Random
Palpha_iR= Random
PI5K= Random
PA= Random
Talin= Random
Gbg_q= Random
Actin= Random
RGS= Random
AC= Random
Ga_1213= Random
MKK7= Random
PIP2_34= Random
Gaq= Random
p120RasGAP= Random
Tpl2= Random
AA= Random
DGK= Random
PTP1b= Random
PIP3_345= Random
Gab1= Random
PLA2*=alpha_1213L and alpha_iL or alpha_1213L and alpha_qL or Tab_12 and Vinc and alpha_iL or Tab_12 and Vinc and alpha_qL
Gas*=Tab_12 and alpha_qL and not alpha_iL or Vinc and not Tab_12 and not alpha_1213L and not alpha_qL
Gbg_i*=alpha_1213L or alpha_iL and not alpha_qL
Integrins*=alpha_iL and not Sek1 and not Tab_12 or Vinc and alpha_1213L and alpha_qL and not alpha_iL or alpha_1213L and alpha_qL and not Tab_12 and not alpha_iL or Sek1 and not Tab_12 and not Vinc and not alpha_1213L and not alpha_iL and not alpha_qL
AC*=Vinc and alpha_1213L and alpha_iL and alpha_qL
Cas*=Vinc and alpha_iL and not alpha_1213L or Vinc and alpha_iL and not alpha_qL
PIP2_45*=Vinc or Sek1 and p120RasGAP or Sos and alpha_qL
PIP3_345*=Sek1 and Tab_12 and not Vinc or Sek1 and Tab_12 and not alpha_qL or alpha_1213L and alpha_iL and not Vinc or alpha_1213L and alpha_iL and not alpha_qL
ARF*=alpha_iL or alpha_qL
Trx*=alpha_iL or alpha_qL
Myosin*=Sek1 and not alpha_qL or Tab_12 and not alpha_qL or Vinc and not alpha_qL or alpha_qL and not Sos or alpha_1213L and alpha_iL and not alpha_qL
Actin*=alpha_iL and alpha_qL
Src*=Sos and not Ral or Sos and not RalGDS or alpha_iL and not Ral or alpha_iL and not RalGDS or Rap1 and p120RasGAP and not Ral or Rap1 and p120RasGAP and not RalGDS or Sek1 and p120RasGAP and not Ral or Sek1 and p120RasGAP and not RalGDS or Tab_12 and Vinc and not Ral or Tab_12 and Vinc and not RalGDS or Vinc and alpha_1213L and not Ral or Vinc and alpha_1213L and not RalGDS or Vinc and alpha_qL and not Ral or Vinc and alpha_qL and not RalGDS
PIP2_34*=Tab_12 and not Vinc and not alpha_1213L or alpha_iL and alpha_qL and not Tab_12
PDK1*=alpha_iL or alpha_qL
CaMKK*=alpha_qL
Akt*=alpha_qL and not alpha_1213L or Sek1 and Sos and Vinc and p120RasGAP and not alpha_qL or Sek1 and Sos and alpha_iL and p120RasGAP and not alpha_qL or Sos and Tab_12 and Vinc and p120RasGAP and not alpha_qL or Sos and Tab_12 and alpha_iL and p120RasGAP and not alpha_qL
WASP*=Sek1 and Sos and Tab_12 and not alpha_1213L or Sek1 and Tab_12 and p120RasGAP and not alpha_1213L or Sos and Tab_12 and alpha_iL and not alpha_1213L or Sos and Tab_12 and alpha_qL and not alpha_1213L or Tab_12 and alpha_iL and p120RasGAP and not alpha_1213L or Tab_12 and alpha_qL and p120RasGAP and not alpha_1213L
Palpha_sR*=alpha_iL and alpha_qL
Palpha_iR*=alpha_iL and alpha_qL
Palpha_1213R*=alpha_iL and alpha_qL
Palpha_qR*=alpha_iL and alpha_qL
B_Arrestin*=Vinc or alpha_1213L or alpha_iL or alpha_qL
IP3R1*=Sos and not alpha_1213L or alpha_iL and not alpha_1213L or Sos and not Tab_12 and not Vinc or Tab_12 and alpha_iL and not Vinc or Vinc and alpha_qL and not Sek1 or Vinc and alpha_qL and not alpha_1213L or alpha_iL and alpha_qL and not Vinc or alpha_iL and not Sek1 and not Vinc
Ca*=alpha_qL and not alpha_iL
CaMK*=alpha_1213L and alpha_qL
PKA*=Vinc and alpha_qL and not alpha_iL or alpha_1213L and alpha_qL and not Vinc
Fak*=Tab_12 and Vinc and not alpha_1213L or alpha_iL and alpha_qL and not Vinc or alpha_iL and alpha_qL and not alpha_1213L
PTPPEST*=alpha_iL and alpha_qL and not Vinc and not alpha_1213L
Cbp*=alpha_iL and not alpha_qL
PAK*=Tab_12 and alpha_iL and not Sek1 or alpha_1213L and alpha_iL and not Sek1 or Tab_12 and Vinc and not Sek1 and not alpha_qL or Vinc and alpha_1213L and not Sek1 and not alpha_qL or Rap1 and Sos and Tab_12 and not Sek1 and not p120RasGAP or Rap1 and Sos and alpha_1213L and not Sek1 and not p120RasGAP
Cdc42*=Sek1 and p120RasGAP and not alpha_qL or Rap1 and Sek1 and Tab_12 and not Sos and not alpha_qL or Rap1 and Sek1 and Tab_12 and not Ral and not Sos and not p120RasGAP
Rac*=Raf_DeP and Raf_Loc and Tab_12 and Vinc and not RalGDS or Raf_DeP and Tab_12 and Vinc and not RalGDS and not alpha_iL or Raf_Loc and Sek1 and Tab_12 and Vinc and not RalGDS or Raf_Loc and Tab_12 and Vinc and alpha_qL and not RalGDS or Sek1 and Tab_12 and Vinc and not RalGDS and not alpha_iL or Tab_12 and Vinc and alpha_qL and not RalGDS and not alpha_iL or Raf_DeP and Raf_Loc and Tab_12 and Vinc and not Sos and not p120RasGAP or Raf_DeP and Tab_12 and Vinc and not Sos and not alpha_iL and not p120RasGAP or Raf_Loc and Sek1 and Tab_12 and Vinc and not Sos and not p120RasGAP or Raf_Loc and Tab_12 and Vinc and alpha_qL and not Sos and not p120RasGAP or Sek1 and Tab_12 and Vinc and not Sos and not alpha_iL and not p120RasGAP or Tab_12 and Vinc and alpha_qL and not Sos and not alpha_iL and not p120RasGAP or Raf_Loc and Raf_Rest and Ral and Tab_12 and Vinc and not RalGDS and not Rap1 or Raf_Loc and Ral and Rap1 and Tab_12 and Vinc and not Raf_Rest and not RalGDS or Raf_Rest and Ral and Tab_12 and Vinc and not Raf_Loc and not RalGDS and not alpha_iL
Pix_Cool*=alpha_1213L and alpha_qL or alpha_iL and alpha_qL
p190RhoGAP*=Vinc and alpha_1213L or Vinc and not alpha_iL or Vinc and not alpha_qL
Graf*=alpha_iL and alpha_qL
RhoGDI*=not alpha_1213L and not alpha_iL and not alpha_qL
Crk*=Vinc and alpha_1213L and not alpha_qL or alpha_1213L and alpha_iL and not alpha_qL
Gbg_1213*=alpha_iL or alpha_qL and not alpha_1213L
Gbg_q*=alpha_iL or alpha_1213L and not alpha_qL
Csk*=Sek1 and alpha_qL or Tab_12 and alpha_qL or Vinc and alpha_qL or alpha_1213L and alpha_qL or alpha_qL and not alpha_iL
PLC_B*=alpha_iL or alpha_1213L and alpha_qL and not Vinc
PLC_g*=Sek1 and Tab_12 and alpha_1213L or Sek1 and Vinc and alpha_1213L or Tab_12 and Vinc and alpha_1213L or Tab_12 and alpha_1213L and not alpha_iL or Tab_12 and alpha_1213L and not alpha_qL or Sek1 and Vinc and not Tab_12 and not alpha_iL and not alpha_qL
DAG*=alpha_iL and not alpha_qL or Tab_12 and Vinc and not alpha_iL or Tab_12 and alpha_1213L and not alpha_iL
DGK*=Tab_12 or Vinc and alpha_1213L or Sek1 and alpha_iL and alpha_qL
EGFR*=alpha_qL and not Sek1 or Sek1 and Tab_12 and alpha_iL or Sek1 and Vinc and alpha_iL or Sek1 and alpha_1213L and alpha_iL
PKC*=Sos and not Tab_12 and not Vinc or Sek1 and alpha_iL and alpha_qL and not Sos or Sek1 and alpha_iL and alpha_qL and not Vinc or alpha_1213L and alpha_iL and alpha_qL and not Sos or alpha_1213L and alpha_iL and alpha_qL and not Vinc
DOCK180*=alpha_1213L and alpha_iL and alpha_qL
alpha_1213R*=alpha_1213L and not alpha_iL or alpha_iL and not Vinc or alpha_qL and not alpha_iL
alpha_iR*=alpha_1213L and not alpha_iL or alpha_iL and not Vinc or alpha_qL and not alpha_iL
alpha_qR*=alpha_1213L and not alpha_iL or alpha_iL and not Vinc or alpha_qL and not alpha_iL
Erk*=alpha_qL or alpha_1213L and not Vinc and not alpha_iL
MKPs*=Vinc and alpha_iL or alpha_1213L and alpha_iL or alpha_iL and alpha_qL
Mek*=alpha_qL and not Sek1 or alpha_qL and not Tab_12 or Sos and Vinc and not Sek1 or Sos and Vinc and not Tab_12 or Sos and alpha_1213L and not Sek1 or Sos and alpha_1213L and not Tab_12 or Sos and alpha_iL and not Sek1 or Sos and alpha_iL and not Tab_12
PTEN*=alpha_iL and not Sek1 or alpha_iL and not Sos or Tab_12 and Vinc and alpha_1213L and alpha_qL and not Sek1 or Tab_12 and Vinc and alpha_1213L and alpha_qL and not Sos
Talin*=alpha_iL and not alpha_qL or alpha_qL and not alpha_1213L
Gbg_s*=alpha_1213L or alpha_iL and not alpha_qL
GRK*=Rap1 and p120RasGAP and not Vinc and not alpha_1213L or Sek1 and Sos and not Vinc and not alpha_1213L or Sek1 and Tab_12 and not Vinc and not alpha_1213L or Sek1 and alpha_iL and not Vinc and not alpha_1213L or Sek1 and alpha_qL and not Vinc and not alpha_1213L
Ga_1213*=Vinc and alpha_1213L and not alpha_qL or alpha_iL and not Vinc and not alpha_1213L
p115RhoGEF*=alpha_iL and alpha_qL
Grb2*=alpha_1213L or alpha_qL or Vinc and alpha_iL
Gab1*=Tab_12 and Vinc and alpha_qL and not alpha_iL or Tab_12 and alpha_1213L and not alpha_iL and not alpha_qL
Gai*=Sos and alpha_qL and not alpha_iL or Vinc and not Sos and not alpha_qL or Tab_12 and alpha_1213L and not Sek1 and not Sos and not alpha_qL
alpha_sR*=alpha_1213L and not alpha_iL or alpha_iL and not Vinc or alpha_qL and not alpha_iL
RGS*=alpha_iL and alpha_qL
Gaq*=Vinc and not alpha_1213L and not alpha_iL or alpha_1213L and alpha_iL and not Tab_12 and not alpha_qL
Shc*=Tab_12 and Vinc and alpha_1213L and not alpha_iL or Tab_12 and Vinc and alpha_1213L and not alpha_qL
IP3*=alpha_1213L and alpha_iL or alpha_1213L and alpha_qL
Mekk4*=alpha_iL or alpha_qL
MLK1*=alpha_iL or alpha_qL
Mekk2*=Sek1 and Tab_12 and not alpha_qL or Tab_12 and Vinc and not alpha_qL or Tab_12 and alpha_1213L and not alpha_qL or Tab_12 and alpha_iL and not alpha_qL
Mekk3*=Vinc and not alpha_qL or alpha_1213L and not alpha_qL or alpha_iL and not alpha_qL
MLK2*=alpha_1213L and alpha_qL or alpha_iL and alpha_qL
MLK3*=alpha_1213L or alpha_iL or alpha_qL
MKK3*=Ral and alpha_1213L or RalGDS and alpha_1213L or Rap1 and alpha_1213L or Sek1 and alpha_1213L or Sos and alpha_1213L or Tab_12 and alpha_1213L or Vinc and alpha_1213L or alpha_1213L and alpha_iL or alpha_1213L and alpha_qL or alpha_1213L and p120RasGAP
MKK6*=Sek1 and alpha_iL or Sos and alpha_iL or Tab_12 and alpha_iL or Vinc and alpha_iL or alpha_1213L and alpha_iL or alpha_iL and alpha_qL
Mekk1*=Rap1 or Sek1 or Vinc or alpha_1213L or p120RasGAP or Sos and alpha_iL or Sos and alpha_qL or Tab_12 and alpha_iL or Tab_12 and alpha_qL or alpha_iL and alpha_qL
MKK7*=Sek1 and alpha_1213L or Sos and alpha_1213L or Tab_12 and alpha_1213L or Vinc and alpha_1213L or alpha_1213L and alpha_iL or alpha_1213L and alpha_qL or alpha_1213L and p120RasGAP
p38*=alpha_1213L and not Tab_12 and not Vinc or alpha_iL and not Tab_12 and not Vinc or alpha_qL and not Tab_12 and not Vinc
cAMP*=alpha_iL and not alpha_1213L or alpha_qL and not alpha_1213L
SAPK*=alpha_iL and not alpha_1213L or alpha_qL and not alpha_1213L or alpha_iL and not Tab_12 and not Vinc or alpha_qL and not Tab_12 and not Vinc
MLCK*=alpha_iL and not Vinc and not alpha_1213L or alpha_qL and not Vinc and not alpha_1213L
Raf*=Sos and Tab_12 or Sos and p120RasGAP and not alpha_1213L and not alpha_qL or Sos and not Sek1 and not alpha_1213L and not alpha_qL or Rap1 and Vinc and alpha_iL and p120RasGAP and not Sos
MLCP*=alpha_iL and alpha_qL and not Sek1 and not Tab_12 and not Vinc and not alpha_1213L or not Sek1 and not Tab_12 and not Vinc and not alpha_1213L and not alpha_iL and not alpha_qL
Ras*=Vinc or alpha_iL or alpha_qL
NIK*=alpha_iL or alpha_qL
Rho*=Vinc and not Tab_12 and not alpha_qL or Tab_12 and not Sek1 and not alpha_1213L and not alpha_iL
PI3K*=Tab_12 or Vinc or alpha_1213L or alpha_iL or alpha_qL or Sek1 and Sos
Nck*=alpha_iL or alpha_qL
PLD*=Sek1 and alpha_1213L or Sos and alpha_1213L or Sek1 and Tab_12 and Vinc or Sek1 and Vinc and alpha_iL or Sek1 and Vinc and alpha_qL or Sek1 and Vinc and p120RasGAP or Sos and Tab_12 and Vinc or Sos and Vinc and alpha_iL or Sos and Vinc and alpha_qL or Sos and Vinc and p120RasGAP
PTP1b*=not alpha_1213L and not alpha_qL or not alpha_iL and not alpha_qL
PDE4*=alpha_1213L and alpha_iL or alpha_1213L and not alpha_qL
p90RSK*=alpha_1213L and alpha_iL and not alpha_qL
PI4K*=Tab_12 or Vinc or alpha_1213L or alpha_iL or alpha_qL
PI5K*=Tab_12 or alpha_iL or alpha_qL or Vinc and alpha_1213L or Sek1 and Sos and not Vinc and not alpha_1213L
PIP_4*=alpha_1213L and not alpha_qL or Sek1 and Vinc and not alpha_qL or alpha_qL and not Tab_12 and not alpha_iL
PKC_primed*=alpha_iL and not alpha_qL or alpha_qL and not alpha_1213L
RasGRF_GRP*=alpha_1213L and alpha_iL or alpha_iL and alpha_qL
Tiam*=Sek1 and Sos and Tab_12 or Sek1 and Sos and alpha_1213L or Sek1 and Sos and alpha_qL or Sek1 and Tab_12 and alpha_iL or Sek1 and Tab_12 and p120RasGAP or Sek1 and alpha_1213L and alpha_iL or Sek1 and alpha_1213L and p120RasGAP or Sek1 and alpha_iL and alpha_qL or Sek1 and alpha_qL and p120RasGAP or Sos and Tab_12 and Vinc or Sos and Vinc and alpha_1213L or Sos and Vinc and alpha_qL or Tab_12 and Vinc and alpha_iL or Tab_12 and Vinc and p120RasGAP or Vinc and alpha_1213L and alpha_iL or Vinc and alpha_1213L and p120RasGAP or Vinc and alpha_iL and alpha_qL or Vinc and alpha_qL and p120RasGAP
Raf_Loc*=alpha_iL and not Vinc or alpha_1213L and alpha_qL and not alpha_iL
Raf_DeP*=alpha_iL and not alpha_1213L or Vinc and alpha_qL and not alpha_iL
Raf_Rest*=alpha_qL and not alpha_iL or not alpha_1213L and not alpha_qL
RalGDS*=Rap1 and Sek1 and not Sos and not Tab_12 or Rap1 and Sek1 and not Sos and not Vinc or Rap1 and Sek1 and not Sos and not alpha_1213L or Rap1 and alpha_iL and not Sos and not Tab_12 or Rap1 and alpha_iL and not Sos and not Vinc or Rap1 and alpha_iL and not Sos and not alpha_1213L or Rap1 and alpha_qL and not Sos and not Tab_12 or Rap1 and alpha_qL and not Sos and not Vinc or Rap1 and alpha_qL and not Sos and not alpha_1213L or Rap1 and p120RasGAP and not Sos and not Tab_12 or Rap1 and p120RasGAP and not Sos and not Vinc or Rap1 and p120RasGAP and not Sos and not alpha_1213L
Ral*=alpha_1213L or alpha_iL or alpha_qL
Rap1*=Sek1 and Vinc and alpha_iL and not Tab_12 or Sek1 and Vinc and alpha_iL and not alpha_qL or Sek1 and alpha_1213L and alpha_iL and not Tab_12 or Sek1 and alpha_1213L and alpha_iL and not alpha_qL
p120RasGAP*=Tab_12 and not Sek1 and not p120RasGAP or Vinc and not Sek1 and not p120RasGAP or alpha_1213L and not Sek1 and not p120RasGAP or alpha_iL and not Sek1 and not p120RasGAP or Sos and not Sek1 and not alpha_qL and not p120RasGAP
Sos*=Tab_12 and Vinc and alpha_1213L or Tab_12 and alpha_qL and not alpha_iL
Sek1*=Ral and alpha_1213L or Rap1 and alpha_1213L or Sek1 and alpha_1213L or Sos and alpha_1213L or Tab_12 and alpha_1213L or Vinc and alpha_1213L or alpha_1213L and alpha_iL or alpha_1213L and alpha_qL or alpha_1213L and p120RasGAP
Tab_12*=alpha_iL and not alpha_qL
Vinc*=Tab_12 and alpha_qL or alpha_1213L and alpha_iL and alpha_qL and not Vinc
"""

model = Model( text=text, mode='sync')

model.initialize()

model.iterate(steps=100, repeat=1)

for state in model.states:
    print (state.PP2A, state.RalGDS, state.p90RSK)

set_trace()